### ISSUE TITLE
Introduce linter for Typescript code

### ISSUE THREAD

**Issue by aliok** [knative-extensions/backstage-plugins#32]
Typescript code is not linted currently.

Notes:
- We already have `lint` scripts in package.json:

https://github.com/knative-extensions/backstage-plugins/blob/84b0e1c7fd01c3e34e4e48682cd04c3afa2ce6d7/backstage/package.json#L22-L23

- Not sure what `lint` and `lint:all` do. Need to understand the difference and pick the correct one.
- Introduce new CI action (in https://github.com/knative-extensions/backstage-plugins/tree/main/.github/workflows) to run the linter.
- Also, adapt existing GitHub actions ([`release`](https://github.com/knative-extensions/backstage-plugins/blob/5c25af695e0681acd68c906ffd8d6e0fcfd647aa/.github/workflows/backstage-release.yaml) and [`release-snapshot`](https://github.com/knative-extensions/backstage-plugins/blob/5c25af695e0681acd68c906ffd8d6e0fcfd647aa/.github/workflows/backstage-release-snapshot.yaml)) to run the linter

So, we should have a separate linter action that is to be run in every PR AND we should also run the linter in the release actions as we double check everything when we release.

**Comment by VamshiReddy02** [comment]
Can I work on this issue?

**Comment by ahmetcihank** [comment]
I am intentioanally breaking lint ; in order to test yarn backstage-cli repo lint --since origin/main script .. No matter how many times i tried, i am getting successfull lint builld..  This one is yarn backstage-cli repo lint, is checking lint for all the project .. @aliok

**Comment by aliok** [comment]
@ahmetcihank let's start with using `lint:all`(`backstage-cli repo lint`)? If we get answers from Backstage community about the `--since origin/main` part and understand why it isn't working, we can switch using that later on.

What do you think?

**Comment by aliok** [comment]
/close
Fixed by https://github.com/knative-extensions/backstage-plugins/pull/48
