### ISSUE TITLE
Eventing nightly manifests are not updated automatically

### ISSUE THREAD

**Issue by aliok** [knative-extensions/backstage-plugins#83]
See https://github.com/knative-extensions/backstage-plugins/pull/82#discussion_r1764513291

Should be done similar to https://github.com/knative-extensions/eventing-kafka-broker/pull/4094

**Comment by aliok** [comment]
How is that done? I couldn't find the job in infra repo. I also checked the actions and scripts in EKB repo.
Gonna ask to productivity group.

**Comment by pierDipi** [comment]
https://github.com/knative-extensions/knobots/blob/c193cd871bc50c688d5b68b69997b861a6393313/.github/workflows/update-nightlies.yaml#L84-L92

**Comment by aliok** [comment]
To be fixed by https://github.com/knative-extensions/knobots/pull/409
